name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '9.7.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -runMode=console -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="1d646ab7-38e7-47db-8329-94a902dce4af" -orgID=743630 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
